project_id = "wtwfnesjxmhqyyymsqsr"

[functions.shopee-scraper]
verify_jwt = false

[functions.generate-listing]
verify_jwt = false

[functions.analyze-shopee-listing]
verify_jwt = false

[functions.generate-product-image]
verify_jwt = false
